version: '3.4'

services:
  mouseandscreen:
    build: .
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - "./data:/app/data"
      - "./usersprites:/app/wwwroot/usersprites"
      - "./backgrounds:/app/wwwroot/backgrounds"
