version: '3.4'

services:
  checker:
    build: .
    ports:
      - "5006:8000"
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
